### ISSUE TITLE
2017 年 04 月，学习总结

### ISSUE THREAD

**Issue by cobish** [cobish/demo#13]
### Vue

绑定自身点击事件，子元素点击不触发，[参考链接](https://cn.vuejs.org/v2/guide/events.html#事件修饰符)

``` vue
<!-- 只当事件在该元素本身（而不是子元素）触发时触发回调 -->
<div v-on:click.self="doThat">...</div>
```

### Css

垂直居中

``` css
.box {
  text-align :center;
  font-size: 0;
}

.box span {
  vertical-align: middle;
  display: inline-block;
  font-size: 16px;
}

.box:after {
  content: '';
  width: 0;
  height: 100%;
  display: inline-block;
  vertical-align: middle;
}
```
